version: '3.1'
services:
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    healthcheck:
      test: exit 0
      interval: 5s
      retries: 1
    # Use the influx cli to set up an influxdb instance.
  influxdb_cli:
    restart: on-failure:3
    links:
      - influxdb
    image: quay.io/influxdb/influxdb:v2.0.3
    # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
    entrypoint: influx setup --bucket mybucket -t mytoken -o de.saefty --username=admin --password=passwordpasswordpassword --host=http://influxdb:8086 -f || true | grep -c '(mybucket|already)'
    # Wait for the influxd service in the influxdb container has fully bootstrapped before trying to setup an influxdb instance with the influxdb_cli service.
    depends_on:
      influxdb:
        condition: service_healthy
volumes:
  influxdb-storage:
